config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :videogames do 
  	collection do 
  	  get 'search' # search videogame model
  	end
  	resources :reviews, except: [:show, :index] # creates a nested resource for reviews; reviews not on videogame pages
  end

  root 'videogames#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :user
	belongs_to :videogame

	validates :rating, :comment, presence: true
	validates :rating, numericality: {
    	only_integer: true,
    	greater_than_or_equal_to: 1,
    	less_than_or_equal_to: 5,
    	message: "can only be a whole number between 1 and 5"
    }
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :videogames
  has_many :reviews, dependent: :destroy # if user deletes account, we want their reviews gone too

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, presence: true
         # Google rails validations to see full list
end

app/models/videogame.rb
class Videogame < ApplicationRecord

	searchkick 

	belongs_to :user
	has_many :reviews

	validates :title, :description, :videogame_difficulty, :publisher, :rating, presence: true

	has_attached_file :image, styles: { medium: "400x600#" } # 400x600 with # will crop the image 
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_videogame
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index # we don't actually have an index, so we can leave this blank
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show # we don't actually have a show, so we can leave this blank
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id # when user writes new review, their id gets associated with that review
    @review.videogame_id = @videogame.id # each new review created with be associated with a @videogame.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @videogame, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @videogame }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to videogame_path(@videogame), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_videogame
      @videogame = Videogame.find(params[:videogame_id])
    end

    def check_user  
      unless (@review.user == current_user) || (current_user.admin?)  # Users can only delete, edit their OWN reviews
        redirect_to root_url, alert: "Sorry, this review belongs to someone else!"
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/videogames_controller.rb
class VideogamesController < ApplicationController
  before_action :set_videogame, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :check_user, except: [:index, :show, :search]
  
  
  def search 
    if params[:search].present? # if the params user search is present
      @videogames = Videogame.search(params[:search]) # display related search params
    else 
      @videogames = Videogame.all # otherwise just display all the games
    end
  end

  # GET /videogames
  # GET /videogames.json
  def index
    @videogames = Videogame.all.paginate(:page => params[:page], :per_page => 8)
  end

  # GET /videogames/1
  # GET /videogames/1.json
  def show
    @reviews = Review.where(videogame_id: @videogame.id).order("created_at DESC")
    
      if @reviews.blank?
        @avg_rating = 0
      else
        @avg_rating = @reviews.average(:rating).round(2)
      end
  end

  # GET /videogames/new
  def new
    @videogame = current_user.videogames.build
  end

  # GET /videogames/1/edit
  def edit
  end

  # POST /videogames
  # POST /videogames.json
  def create
    @videogame = current_user.videogames.build(videogame_params)

    respond_to do |format|
      if @videogame.save
        format.html { redirect_to @videogame, notice: 'Videogame was successfully created.' }
        format.json { render :show, status: :created, location: @videogame }
      else
        format.html { render :new }
        format.json { render json: @videogame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videogames/1
  # PATCH/PUT /videogames/1.json
  def update
    respond_to do |format|
      if @videogame.update(videogame_params)
        format.html { redirect_to @videogame, notice: 'Videogame was successfully updated.' }
        format.json { render :show, status: :ok, location: @videogame }
      else
        format.html { render :edit }
        format.json { render json: @videogame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videogames/1
  # DELETE /videogames/1.json
  def destroy
    @videogame.destroy
    respond_to do |format|
      format.html { redirect_to videogames_url, notice: 'Videogame was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_videogame
      @videogame = Videogame.find(params[:id])
    end

    def check_user 
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, only admins can do that"
      end
    end
        
    # Never trust parameters from the scary internet, only allow the white list through.
    def videogame_params
      params.require(:videogame).permit(:title, :description, :videogame_difficulty, :publisher, :rating, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/videogames_helper.rb
module VideogamesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RetroReviews", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
         <% if current_user.admin? %>
          <li><%= link_to "New VideoGames", new_videogame_path, class: "active" %></li>
         <% end %>
          <li><%= link_to "My Account", edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Log In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <%= form_tag search_videogames_path, method: :get, class:"navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
        </p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title>VideogameReview</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Audiowide" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>

  <div class="container">
    	<% flash.each do |key, value| %>
  	    <div class="alert alert-<%= key %> alert-dismissable">
  	        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  	        <%= value %>
  	    </div>
  	<% end %>
  

    <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@videogame, @review]) do |f| %>  <!-- need this for our nested route -->
  <% if review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <div id="star-rating"></div>
  </div><br>

  <div class="form-group form-group-lg">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: "form-control input-lg" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: 'https://s3.amazonaws.com/wills-videogames/stars',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1> <br>

<%= render 'form', review: @review %> <br>

<%= link_to 'Back', videogame_path(@videogame), class: "btn btn-primary" %>

app/views/reviews/new.html.erb
<h1>Create a New Review</h1><br>

<%= render 'form', review: @review %> <br>

<%= link_to 'Back', videogame_path(@videogame), class: "btn btn-primary" %>

app/views/videogames/_form.html.erb
<%= form_for @videogame, html: { multipart: true } do |f| %>
  <% if videogame.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(videogame.errors.count, "error") %> prohibited this videogame from being saved:</h4>

      <ul>
      <% videogame.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "e.g. Super Mario Bros." %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control input-lg", placeholder: "..." %>
  </div>

  <div class="form-group">
    <%= f.label :videogame_difficulty %>
    <%= f.text_field :videogame_difficulty, class: "form-control", placeholder: "e.g. easy, average, hard, difficult" %>
  </div>

  <div class="form-group">
    <%= f.label :publisher %>
    <%= f.text_field :publisher, class: "form-control", placeholder: "e.g. Company that created the game" %>
  </div>

  <div class="form-group">
    <%= f.label :rating %>
    <%= f.text_field :rating, class: "form-control", placeholder: "e.g. Everyone, Teen, Mature, Adults Only, etc.." %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videogames/edit.html.erb
<h1>Editing Videogame</h1>

<%= render 'form', videogame: @videogame %> <br>

<%= link_to 'Show', @videogame, class: "btn btn-primary" %> |
<%= link_to 'Back', videogames_path, class: "btn btn-primary" %>

app/views/videogames/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
  	<h1>Retro Video Game Reviews</h1>
  	<p>The <strong>best</strong> place to find your favourite video game reviews!</p>
  	<p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
  <% end %>


<div class="row">
  <% @videogames.each do |videogame| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
      	<%= link_to (image_tag videogame.image.url(:medium), class: 'image'), videogame %>
      </div>
    </div>
  <% end %>
</div> <!-- row -->

<%= will_paginate %>

app/views/videogames/new.html.erb
<h1>New Videogame</h1>

<%= render 'form', videogame: @videogame %> <br>

<%= link_to 'Back', videogames_path, class: "btn btn-primary" %>

app/views/videogames/search.html.erb
<div class="row">
  <% @videogames.each do |videogame| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
      	<%= link_to (image_tag videogame.image.url(:medium), class: 'image'), videogame %>
      </div>
    </div>
  <% end %>
</div> <!-- row -->

app/views/videogames/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @videogame.image.url(:medium) %> <br/>
        <div class="star-rating" data-score= <%= @avg_rating %> ></div>
        <em><%= "#{@reviews.length} reviews" %></em> <br/>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                  <td><strong>Title:</strong></td>
                  <td><%= @videogame.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @videogame.description %></td>
              </tr>
              <tr>
                <td><strong>Videogame difficulty:</strong></td>
                <td><%= @videogame.videogame_difficulty %></td>
              </tr>
              <tr>
                <td><strong>Publisher:</strong></td>
                <td><%= @videogame.publisher %></td>
              </tr>
              <tr>
                <td><strong>Rating:</strong></td>
                <td><%= @videogame.rating %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write your own Review", new_videogame_review_path(@videogame), class: "btn btn-success" %> <br><br>

          <% if user_signed_in? %>
            <% if (@videogame.user == current_user) || (current_user.admin?) %>
              <%= link_to 'Edit Game', edit_videogame_path(@videogame), class: "btn btn-primary" %>
              <%= link_to "Delete Game", videogame_path(@videogame), method: :delete, class: "btn btn-danger" %>
            <% end %>
          <% end %>

          <%= link_to 'Back', videogames_path, class: "btn btn-primary" %>

        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @videogame.title %></h1>
        <h4><%= @videogame.description %></h4>

        <% if @reviews.blank? %>
          <h3>There are no reviews yet - add the first?</h3>
          <%= link_to "Write Review", new_videogame_review_path(@videogame), class: "btn btn-success" %>
        <% else %>
          <br><br><br>
          <% @reviews.each do |review| %>
            <tr>
              <td>
                <h4>
                  <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                </h4>
                <p><%= review.created_at.strftime("%-m/%-d/%y") %></p>
              </td>
            </tr>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.comment %></p>

              <% if user_signed_in? %>
                <% if (review.user == current_user) || (current_user.admin?) %>
                  <%= link_to "Edit", edit_videogame_review_path(@videogame, review) %>
                  <%= link_to "Delete", videogame_review_path(@videogame, review), method: :delete %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>


      </div>
    </div> <!-- row -->
  </div> <!-- panel-body -->
</div> <!-- panel-default -->




<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/wills-videogames/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>